//Variable Assignment
BRANCH='dev'
NAME='test'

pipeline {
    agent any

    stages {
        stage('Build'){
            steps{
                echo 'Build Done'
            }
        }
        stage('Test'){
            // only run wen condition fulfilled
            when {
                expression {
                    BRANCH == 'dev' && NAME == 'test'
                }
            }
            steps{
                echo 'Test Done'
            }
        }
        stage('Deploy'){
            steps{
                echo 'Deploy Done'
            }
        }
    }
}