pipeline{

    agent any

    environment {
        registry = "someshdokerbox/test"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages{
        stage("Build Docker Image") {
            steps {
                dockerImage = docker.build registry + ":$BUILD_NUMBER"
            }
        }
        stage("Push Image") {
            steps {
                script {
                        docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
