dockerImage = ''

pipeline{

    agent any

    environment {
        registry = "someshdokerbox/test"
        registryCredential = 'docker-hub'
    }

    stages{
        stage("Build Docker Image") {
            steps {
                sh "chmod 777 /var/run/docker.sock"
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage("Push Image") {
            steps {
                script {
                        docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
