def gv

pipeline {

    agent any

    parameters {
        string (name: "NAME", defaultValue:"default", description: "Here is the description")
    }

    stages {
        stage("Init"){
            steps{
                script {
                    gv = load "load-groovy/script.groovy"
                }    
                echo "here"
            }
        }
        stage("Build"){
            steps{
                script {
                    gv.buildApp()
                }    
            }
        }
        stage("Test"){
            steps{
                script {
                    gv.testApp()
                }    
            }
        }
        stage("Release"){
            steps{
                script {
                    gv.releaseApp()
                }    
            }
        }
    }
}