def gv

pipeline {

    agent any

    parameters {
        string (name: "NAME", defaultValue:"default", description: "Here is the description")
    }

    stages {
        stage("Init"){
            steps{
                echo "here"
            }
        }
        stage("Build"){
            steps{
                echo "here"
            }
        }
        stage("Test"){
            steps{
                echo "here"
            }
        }
        stage("Release"){
            steps{
                echo "here"
            }
        }
    }
}