pipeline {
    
    agent any

    environment {
        VERSION = '1.0'
    }

    stages {
        stage("Build"){
            steps{
                echo "Checking Version . . ."
                echo "Version is ${VERSION}"
            }
        }   
    }
}