InputValue=false

pipeline{
    agent{
        label "node"
    }
    stages{
        stage("First Step"){
            steps{
                script {
                    def InputValue = input(
                        id: 'userInput',
                        message: 'User input required - Some Yes or No question?',
                        parameters: [
                            choice(name: 'CHOICE', choices: [true, false], description: 'Enter your Choice'),
                        ]
                    )
                }
            }
        }
        stage("Second Step"){
            when {
                expression {
                    InputValue
                }
            }
            steps{
                echo "InputValue is ${InputValue} That is why it Ran"   
            }
        }
    }
}